import { formatTrailers, type TrailerInput } from "../trailer/format.js"
import type { Layer } from "../types.js"

const LABEL: Record<Layer, string> = {
  A: "Mechanical changes",
  B: "Light human review",
  C: "Human review required",
}

export type BuildCommitMessageArgs = TrailerInput & { generatedAt: Date }

export function buildLayerCommitMessage(args: BuildCommitMessageArgs): string {
  const prNum = args.sourcePR.split("#")[1] ?? "?"
  const date = args.generatedAt.toISOString().slice(0, 10)
  const title = `[Layer ${args.layer}] ${LABEL[args.layer]} — vibereview/pr-${prNum}`
  const body =
`Generated by vibereview on ${date}.
This commit groups hunks classified as Layer ${args.layer}.
See PR description for the full manifest.`
  const trailers = formatTrailers(args)
  return `${title}\n\n${body}\n\n${trailers}\n`
}
