import { describe, it, expect } from "vitest"
import { buildLayerCommitMessage } from "../../../src/apply/commit.js"

describe("buildLayerCommitMessage", () => {
  it("includes title, body, and all trailers", () => {
    const msg = buildLayerCommitMessage({
      layer: "A",
      sourcePR: "cowprotocol/cowswap#1234",
      sourceHead: "def456abc789",
      hunkIds: ["h_1", "h_2"],
      toolVersion: "0.1.0",
      provider: "claude",
      model: "claude-opus-4-7",
      generatedAt: new Date("2026-05-17T14:32:00Z"),
    })
    expect(msg).toMatch(/^\[Layer A\] Mechanical changes — vibereview\/pr-1234/m)
    expect(msg).toContain("Vibereview-Layer: A")
    expect(msg).toContain("Vibereview-Hunks: h_1,h_2")
    expect(msg).toContain("Generated by vibereview on 2026-05-17")
  })

  it("uses the right label for each layer", () => {
    const a = buildLayerCommitMessage({ layer: "A", sourcePR: "x/y#1", sourceHead: "abc",
      hunkIds: [], toolVersion: "0", provider: "claude", model: "m", generatedAt: new Date() })
    const b = buildLayerCommitMessage({ layer: "B", sourcePR: "x/y#1", sourceHead: "abc",
      hunkIds: [], toolVersion: "0", provider: "claude", model: "m", generatedAt: new Date() })
    const c = buildLayerCommitMessage({ layer: "C", sourcePR: "x/y#1", sourceHead: "abc",
      hunkIds: [], toolVersion: "0", provider: "claude", model: "m", generatedAt: new Date() })
    expect(a).toMatch(/^\[Layer A\] Mechanical changes/m)
    expect(b).toMatch(/^\[Layer B\] Light human review/m)
    expect(c).toMatch(/^\[Layer C\] Human review required/m)
  })
})
